dbt_project:
  outputs:
    dev:
      dataset: pipeline_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: valid-hall-374418
      threads: 1
      type: bigquery
  target: dev
