dbt_project:
  outputs:
    dev:
      dataset: pipeline_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: data-pipeline-interactive
      threads: 1
      type: bigquery
    prod:
      dataset: pipeline_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: prod
      project: data-pipeline-prod
      threads: 1
      type: bigquery
    target: dev
